merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('about-us/', views.about, name='about'),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:id>/change/', views.listing_update, name='listing-update'),
    path('listings/<int:id>/delete/', views.listing_delete, name='listing-delete'),
    path('contact-us/', views.contact, name='contact'),
    path('redirection/', views.redirection, name='redirection-users'),
]

listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):
    class Genre(models.TextChoices):
        FUNK = 'FK'
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        RAI = 'RA'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2023)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):
    class Type(models.TextChoices):
        Records = 'REC'
        Clothing = 'CL'
        Posters = 'PT'
        Miscellaneous = 'MC'

    name = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=500)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2023)], blank=True
    )
    type = models.fields.CharField(choices=Type.choices, max_length=5)

    def __str__(self):
        return f'{self.name}'

    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

listings/forms.py
from django import forms
from listings.models import Band, Listing

class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
   class Meta:
     model = Band
     # fields = '__all__' # supprimez cette ligne
     exclude = ('active', 'official_homepage')  # ajoutez cette ligne

class ListingForm(forms.ModelForm):
   class Meta:
     model = Listing
     exclude = ('sold',)

listings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from listings.models import Band, Listing
from listings.forms import BandForm, ListingForm, ContactUsForm
from django.core.mail import send_mail
from django.shortcuts import redirect


def band_list(request):
    bands = Band.objects.all()
    return render(request,
                  'listings/band_list.html',
                  {'bands': bands})


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html',
                  {'band': band})  # nous passons l'id au modèle


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('band-detail', band.id)
    else:
        form = BandForm()

    return render(request,
            'listings/band_create.html',
            {'form': form})


def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                'listings/band_update.html',
                {'form': form})


def band_delete(request, id):
    band = Band.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/band_delete.html',
                    {'band': band})


def listing_list(request):
    titles = Listing.objects.all()
    return render(request, 'listings/listing_list.html',
                  {'titles': titles})


def listing_detail(request, id):
    title = Listing.objects.get(id=id)
    return render(request, 'listings/listing_detail.html',
                  {'title': title})


def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            # créer un nouvel « objet listing » et la sauvegarder dans la db
            listing = form.save()
            # redirige vers la page de détail de lobjet que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()

    return render(request,
            'listings/listing_create.html',
            {'form': form})


def listing_update(request, id):
    objet = Listing.objects.get(id=id)

    if request.method == 'POST':
        form = ListingForm(request.POST, instance=objet)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('listing-detail', objet.id)
    else:
        form = ListingForm(instance=objet)

    return render(request,
                'listings/listing_update.html',
                {'form': form})


def listing_delete(request, id):
    title = Listing.objects.get(id=id)

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        title.delete()
        # rediriger vers la liste des groupes
        return redirect('listing-list')
    return render(request,
                  'listings/listing_delete.html',
                  {'title': title})


def contact(request):
    # # ajoutez ces instructions d'impression afin que nous puissions jeter un coup d'oeil à « request.method » et à « request.POST »
    # print('La méthode de requête est : ', request.method)
    # print('Les données POST sont : ', request.POST)

    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
            # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).

        return redirect('redirection-users')  # ajoutez cette instruction de retour
    else:
        # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()
    return render(request,
                  'listings/contact.html',
                  {'form': form})


def redirection(request):
    return render(request, 'listings/redirection.html', )


def about(request):
    return render(request, 'listings/about.html', )

listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>À propos</h1>
    <p>Nous apprécions merch !</p>

{% endblock %}

listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Créer un nouveau groupe</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Supprimer le groupe</h1>

  <p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
 </form>

<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
 <li>Biographie : {{ band.biography }}</li>
 <br>
 {% if band.official_homepage %}
 <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
 {% endif %}
</ul>
<br>

<h2>Liste des annonces du groupe {{ band.name }}</h2>
<ul>
    {% for listing in band.listing_set.all %}
     <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.name }}</a></li>
    {% endfor %}
</ul>

<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>
<a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>
<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<ul>
    {% for band in bands %}
     <li>
         <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
         - <a href="{% url 'band-update' band.id %}">[modifier]</a>
     </li>
    {% endfor %}
</ul>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
{% endblock %}

listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Mise à jour du groupe</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>
{% endblock %}

listings/templates/listings/base.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
</head>
<body>
    <nav>
     <a href="{% url 'band-list' %}">Groupes</a>
     <a href="{% url 'listing-list' %}">Objets</a>
     <a href="{% url 'contact' %}">Contactez-nous</a>
     <a href="{% url 'about' %}">A propos de nous</a>
    </nav>

    {% block content %}{% endblock %}
</body>

<!--<a href="{% url 'band-list' %}">Retour à tous les groupes</a>-->
<!--<br>-->
<!--<a href="{% url 'listing-list' %}">Retour aux annonces</a>-->
</html>

listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Envoyer">
</form>

{% endblock %}

listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Créer un nouvel objet</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Supprimer l'objet </h1>

  <p>Etes-vous sûr de vouloir supprimer l'objet : {{ listing.name }} ?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
 </form>

<a href="{% url 'listing-list' %}">Retour aux annonces</a>

{% endblock %}

listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ title.name }}</h2>

<ul>
 <li>Groupe : {{ title.band }}</li>
 <li>Description : {{ title.description }}</li>
 <li>Année : {{ title.year }}</li>
 <li>Type : {{ title.get_type_display }}</li>
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'listing-update' title.id %}">Modifier cet objet</a>
<a href="{% url 'listing-delete' title.id %}">Supprimer cet objet</a>
<a href="{% url 'listing-list' %}">Retour aux annonces</a>


{% endblock %}

listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Objets Groupes :</h1>
    <ul>
        {% for title in titles %}
        <li>
            <a href="{% url 'listing-detail' title.id %}"> {{ title.name }} </a>
            - <a href="{% url 'listing-update' title.id %}">[modifier]</a>

        </li>
        {% endfor %}
    </ul>

<a href="{% url 'listing-create' %}">Créer un nouvel objet</a>


{% endblock %}

listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Mise à jour des objets</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>
{% endblock %}

listings/templates/listings/redirection.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Votre email a été envoyé </h1>
    <p> Ton thé a-t'il oté ta toux !</p>

{% endblock %}